### ISSUE TITLE
PoS - rename validator "total_deltas" to "total_stake"

### ISSUE THREAD

**Issue by tzemanovic** [namada-net/namada#158]

**Comment by brentstone** [comment]
I am in favor of keeping the name `total_deltas` but instead renaming variables in code to accurately indicate when something is actually the total stake, such as in:

`total_stake = total_deltas.get(epoch)`

This is how I have been proceeding so far in #388. Alternatively, we could also rename the `get` method of `EpochedDelta` to something like `get_sum`, since this is what is happening more accurately.
